### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by NoPantsMcDance** [betterphp/NoFloatingTrees#1]
2012-03-31 00:17:22 [INFO] [NoFloatingTrees] Enabling NoFloatingTrees v0.8
2012-03-31 00:17:22 [SEVERE] Error occurred while enabling NoFloatingTrees v0.8 (Is it up to date?)
java.lang.NullPointerException
    at uk.co.jacekk.bukkit.NoFloatingTrees.util.NoFloatingTreesConfig.<init>(NoFloatingTreesConfig.java:42)
    at uk.co.jacekk.bukkit.NoFloatingTrees.NoFloatingTrees.onEnable(NoFloatingTrees.java:34)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:374)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:361)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by betterphp** [comment]
Do you see this error the second time you start the server ?

I think it might just be that I didn't handle the config file not existing very well.

**Comment by betterphp** [comment]
Oh no, I see what I did. Tried to use the log file before it was available ;)

You can safely ignore the error and I will upload a fix now.

**Comment by betterphp** [comment]
Done :D

Takes 5 minutes to fix it but we have to wait 4 hours for BukkitDev to approve the file /me frowns
